### ISSUE TITLE
Not working with Solr 8.5 due to CSP restrictions

### ISSUE THREAD

**Issue by janhoy** [yasa-org/yasa#13]
Try to run with Solr 8.5 and the GUI won't load due to CSP restrictions:
![yasa-solr-csp](https://user-images.githubusercontent.com/409128/83244404-9a5ed680-a19f-11ea-8557-deb988022012.png)

**Comment by kezhenxu94** [comment]
I've tried the latest codes, it works well with Solr 8.5

**Comment by kezhenxu94** [comment]
Not working, test in wrong way

**Comment by epugh** [comment]
@kezhenxu94 We discovered with Quepid that our JSON calls to Solr started failing because the `wt=json` response isn't actually the right mimetype.  It's often a plain text mimetype.  (https://github.com/apache/lucene-solr/blob/master/solr/server/solr/configsets/_default/conf/solrconfig.xml#L1167).   So we have users run a command to change it to JSON.   

https://github.com/o19s/quepid/wiki/Troubleshooting-Solr-and-Quepid#connectivity

Not sure if that is the same issue as what you are seeing, but wanted to share!

**Comment by kezhenxu94** [comment]
@epugh thanks for sharing, the restricted are actually some static resources in this case, e.g. css, js, and fonts, and I'm figuring out how to do this, anyway, thanks for sharing 😄
